spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: kgfpart2
  jpa:
    hibernate:
      ddl-auto: create   # options: validate, update, create, create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mughallmohsin938@gmail.com
    password: urplbyykuhehsjsw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8001
jwt:
  secret: U2FmZVJpZGVTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24yMDI2U3ByaW5nQm9vdA==
  expiration: 86400000
app:
  verification:
    base-url: http://localhost:62219
    token-expiry-hours: 24